### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by alexsomeoddpilot** [dmapper/yamlify#2]
I'm having trouble using this transform in a watchify setup.

```
SyntaxError: Unexpected token (1:6) while parsing file: /src/process/processes.yaml
```

**Comment by cray0000** [comment]
seems that `(1:6)` is the value of something, since it has `:` in it you have to put the whole value in quotes, so it should be `"(1:6)"`.

**Comment by alexsomeoddpilot** [comment]
I determined that I had the transform lower in the queue of transforms, and thus the Javascript parser was throwing a fit.
